"""Build the research register and Markdown views from reviewable source data.

Standard library only. Scores are hypotheses, never investment recommendations.
"""
from pathlib import Path
import csv, json, hashlib

ROOT = Path(__file__).resolve().parents[1]
DATE = '2026-09-11'
def write(path, text):
    p = ROOT / path
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding='utf-8')

# id | sector | area | asset | mechanism | capture | measurable KPI | quality guardrail | falsifier | experiment | horizon | evidence IDs
AREA_DATA = '''
H01|Health Care|Pharmaceuticals and biotechnology|Longitudinal experiments, failed compounds, clinical cohorts and trial infrastructure|Use multimodal models and active learning to improve target selection, molecule design and trial stratification. The valuable outcome is more clinically useful candidates per research euro.|Patent-protected products and differentiated clinical outcomes can retain value, but payers and competing treatments can absorb the gain.|Phase II-to-III transition rate by entry cohort; risk-adjusted pipeline value per R&D euro; time and spend to kill weak programmes|No deterioration in toxicity, patient outcomes or trial representativeness|More preclinical candidates without improved prospective clinical translation, or costs move into expensive validation|Compare AI-assisted and conventional programmes matched on modality, therapeutic area, stage and vintage. Include abandoned programmes.|3–7 years for clinical proof|S03
H02|Health Care|Medical devices, diagnostics and surgical platforms|Installed instruments, imaging or procedure data, clinician relationships and service networks|AI can improve image reconstruction, diagnostic workflow and procedure planning, allowing each installed system to handle more useful clinical work.|Premium features, service contracts and procedure-linked consumables may capture a share of customer throughput gains.|Quality-adjusted procedures per installed unit; repeat-scan rate; software attach and renewal rate|Sensitivity and specificity by subgroup, adverse events and clinician review time|Clinical workflow savings fail to increase billable throughput, or reimbursement falls by the same amount|Use paired-reader studies and hospital deployment cohorts with equivalent case mix. Separate diagnostic accuracy from billing activity.|1–4 years|S03
H03|Health Care|Life science tools, CROs and laboratory platforms|Instrument footprints, assay protocols, laboratory workflows and trial operations|AI can automate experimental design, improve assay yield and shorten trial recruitment or monitoring work.|Consumables, software and workflow switching costs can monetize higher laboratory utilization. CROs must retain savings despite hourly contracts.|Successful experiments per instrument-day; trial enrollment time; service contribution per project|Reproducibility, protocol deviations and trial dropout rates|Tools become interchangeable, customer data cannot be reused, or buyers reprice every saved hour|Compare matched assays or trial sites before and after deployment and account for staffing, protocol and demand differences.|1–4 years|S03
H04|Health Care|Healthcare providers, services and managed care|Care-delivery workflows, appointment capacity and claims or clinical records under restricted rights|AI can reduce documentation and scheduling work and improve appropriate care coordination.|Providers may fill scarce clinical capacity. Payers may reduce avoidable cost, subject to medical-loss rules, contracts and consumer protections.|Clinician time per completed encounter; waiting time; risk-adjusted cost per member|Patient outcomes, appeal overturns, denial errors and equitable access|Savings depend on inappropriate denials, revenue coding inflation or quality deterioration|Use controlled clinics or member cohorts, with independent clinical adjudication and case-mix adjustment.|1–3 years|S14
F01|Financials|Property insurance and reinsurance|Claims histories, exposure records, distribution and underwriting expertise|AI can interpret submissions, find fraud and improve risk selection. Reinsurance has sparse tail labels, unlike frequent retail claims.|Better risk selection and lower expense ratios may survive renewals where proprietary information and underwriting discipline persist.|Accident-year loss ratio adjusted for price and mix; claims expense per resolved claim; new-business risk-adjusted return|Reserve adequacy, appeal outcomes, tail concentration and fairness|Apparent gains come from reserve releases, a hard pricing cycle, risk exclusion or hidden correlated exposures|Compare matched underwriting cohorts and claims outcomes. Require a catastrophe-normalized view and adverse development analysis.|1–3 years for expense gains; 3–5 for loss emergence|S14;S15
F02|Financials|Life insurance, wealth and asset management|Policyholder relationships, adviser networks, investment workflows and administrative records|AI can improve adviser capacity, policy servicing and client retention. Life underwriting needs long observation periods, while investment research faces crowded signals.|Distribution and recurring administration can retain savings. Investment alpha is a separate, much harder hypothesis.|Cost per policy or account; adviser assets serviced; persistency or organic net flows|Suitability complaints, lapse quality, solvency and performance net of fees|Higher adviser output fails to improve net flows, pricing falls, or model portfolios homogenize risk|Evaluate matched adviser books. Separate market appreciation from flows and separate servicing improvements from claimed investment alpha.|1–4 years|S14;S09
F03|Financials|Banking and lending|Deposit franchises, transaction histories, credit outcomes and regulated distribution|AI can improve fraud controls, service capacity and credit decisions while automating document-heavy operations.|A durable funding franchise and embedded relationships can retain some gains, but competition and credit cycles dominate weak underwriting.|Cost-to-income at constant business mix; fraud loss per transaction; vintage default and risk-adjusted return|Fair lending, model drift, capital use and false credit declines|Efficiency gains vanish after provisions or require unsafe automated lending|Match credit vintages and service cohorts. Hold funding costs and risk appetite constant; separate ML upgrades from interest-rate effects.|1–3 years|S09
F04|Financials|Payments and transaction networks|Network-level transactions, merchant relationships and fraud outcome signals|AI can identify fraud and reduce false declines using context that individual merchants or issuers cannot easily reproduce.|Risk-service fees and higher legitimate transaction volume can monetize improved authorization quality.|Fraud basis points at fixed approval rate; false declines; net risk-service revenue per client|Dispute losses, merchant attrition, rebates and latency|Fraud shifts rather than falls, network fees compress, or account-to-account rails bypass the service|Use randomized or matched authorization policies with equal fraud budgets. Measure issuer and merchant outcomes as well as network revenue.|6–24 months|S10
F05|Financials|Credit data, exchanges and financial intelligence|Permissioned credit histories, market records, ratings expertise and licensed data feeds|AI can turn curated records into underwriting, research and compliance decisions with less manual reconciliation.|Licenses, data entitlements and embedded decision workflows can support paid tools. Public facts alone are a weak moat.|Paid AI attach; net retention; analyst or onboarding time at fixed error rate|Data provenance, model leakage, licensing costs and customer concentration|Customers recreate the product with alternative data, or suppliers capture the AI revenue|Compare incumbent and challenger performance on identical lawful datasets. Then add proprietary features to isolate their marginal value.|1–3 years|S04;S09
I01|Information Technology|Legal, tax and professional information|Editorial enrichment, citations, licensed archives and trusted professional workflows|AI can convert reference content into validated research, drafting and compliance work.|Paid workflow expansion can exceed lost search seats if customers trust the output and need the underlying content rights.|Net revenue per customer after seat changes; paid AI renewals; verified task completion cost|Citation accuracy, professional liability and content licensing terms|Generic agents obtain equivalent trusted answers more cheaply, or seat cannibalization exceeds AI monetization|Benchmark against generic models and new specialist entrants on blinded jurisdiction-specific tasks, including total human checking time.|6–24 months|S04;S05;S06
I02|Information Technology|Vertical software and financial administration|Domain-specific systems of record, transaction context and implementation knowledge|AI can perform more bookkeeping, payroll, compliance or industry-specific administration inside the existing workflow.|Outcome or transaction pricing can expand revenue per customer, if seat loss and model costs remain smaller.|Net revenue per customer; verified tasks completed per support hour; AI contribution margin|Reconciliation errors, filing accuracy and human escalation costs|Cheaper agents use the system only as a low-price database or customers eliminate more seats than they buy AI services|Track customer cohorts, usage rights and total bill changes. Include customers that cancel or downgrade.|6–24 months|S07;S06
I03|Information Technology|Enterprise systems and workflow orchestration|Business process definitions, permissions, integrations and systems of record|AI agents can coordinate transactions across enterprise workflows with existing authorization and audit controls.|Control of execution and compliance may preserve economics even as user interfaces change.|End-to-end task completion; AI net new contract value; total customer spend after seat changes|Rollback success, auditability, inference cost and unauthorized actions|A cross-vendor agent captures the interface and forces the incumbent into commodity storage pricing|Measure completed workflows with customer-level cash cost, including integration and human exception handling.|6–30 months|S08
I04|Information Technology|EDA, engineering and design software|Solvers, design-rule knowledge, verified toolchains and workflow integration|AI can explore design spaces and generate candidate implementations while deterministic tools validate constraints.|Validated outputs and deep workflow integration can support software pricing or more design volume.|Engineer hours per verified design; first-pass signoff; paid AI attach|Power, performance and area constraints, defects and verification expense|Compute and verification costs offset time savings, or customers retain all productivity gains|Compare designs under identical constraints, compute budgets and signoff criteria. Keep customer IP permissions explicit.|1–3 years|S16
I05|Information Technology|Semiconductor fabrication, equipment and process control|Process recipes, yield histories, metrology and installed production equipment|AI can improve defect detection, equipment uptime and process-window search.|Leading yields and equipment service value may raise returns. This is separate from selling more capacity to AI customers.|Yield at equivalent node and product; good dies per tool-hour; unplanned downtime|Reliability, node transitions, model drift and customer confidentiality|Yield gains reflect product mix or new equipment, while capital intensity and depreciation consume the benefit|Compare matched tools, wafers and process stages. Account for learning curves that existed before AI deployment.|1–4 years|S16
I06|Information Technology|Cloud and diversified technology platforms|Cloud infrastructure, developer ecosystems, distribution and operating datasets|AI can improve internal engineering and customer products while platform distribution enables deployment.|Usage revenue and ecosystem control can capture value, but compute investment and model competition can absorb it.|Cash return on incremental AI infrastructure; cost per completed task; non-AI segment productivity|Utilization, depreciation, power availability and internal transfer pricing|Revenue grows while cash returns fall, or AI cannibalizes profitable products|Value cloud, software, advertising and retail separately. Do not count the same AI revenue as both customer savings and supplier profit.|1–4 years|S08;S17
I07|Information Technology|IT services, consulting and outsourced processes|Implementation expertise, customer access and operational delivery knowledge|AI can reduce the labor required for delivery and increase project throughput.|Fixed-price or outcome contracts can retain savings. Hourly billing may shrink revenue as productivity improves.|Gross profit per project; revenue and profit per delivery employee; outcome-contract share|Rework, utilization, bench costs and client renewal|Clients insource using AI, billable hours collapse, or savings are fully passed through at renewal|Compare contract types and project cohorts, controlling for offshoring, utilization and wage changes.|6–24 months|S01;S02;S18
I08|Information Technology|Cybersecurity and identity software|Threat telemetry, endpoint distribution, response workflows and security expertise|AI can triage incidents, correlate signals and accelerate response while attackers also use AI.|Trusted security platforms can retain spending if detection quality and integration outperform cheaper bundled tools.|False positives at fixed detection rate; analyst hours per incident; net retention|Missed incidents, adversarial evasion and correlated outage risk|Automation adds alert volume, misses novel attacks or cannot offset platform bundling|Use independent adversarial evaluations and production incident cohorts. Never substitute demo detection for real-world coverage.|6–24 months|S13
D01|Industrials|Industrial automation and electrification|Installed controls, engineering channels, operational telemetry and service expertise|AI can improve commissioning, anomaly detection and energy optimization across existing equipment.|Installed-base integration and service contracts may monetize customer downtime savings.|Commissioning hours; unplanned downtime per operating hour; recurring software attach|Safety constraints, latency, uptime and customer data permissions|Value requires costly plant-by-plant integration or customers use independent software instead|Compare similar production cells before staged rollout, controlling for maintenance and capital upgrades.|1–4 years|S16;S17
D02|Industrials|Agricultural, construction and mining machinery|Equipment fleets, dealer networks, field telemetry and work-cycle knowledge|Computer vision and autonomy can reduce inputs, operator burden and idle time.|Equipment premiums, subscriptions and services may retain a share of per-acre or per-tonne savings.|Input cost per acre at equal yield; tonnes per machine-hour; paid software renewals|Crop outcomes, incidents, uptime and total retrofit cost|Customer savings do not support durable pricing or autonomy needs expensive supervision|Use paired fields or work sites with equal conditions. Measure whole-season or whole-shift results rather than selected demonstrations.|1–4 years|S17
D03|Industrials|Logistics, parcel, rail and transport networks|Route density, shipment flows, depot networks and asset histories|AI can improve routing, load matching, maintenance and network placement.|Dense networks and service reliability can retain savings, although large customers and fuel contracts may demand pass-through.|Cost per delivered unit at fixed service level; empty miles; asset utilization|On-time delivery, damage, overtime and fuel-price effects|Rivals deploy identical routing software and bids reset lower, or savings only reflect demand recovery|Compare matched routes and depots with volume, distance, weather, fuel and service mix held constant.|6–30 months|S11
D04|Industrials|Civil aerospace and long-life equipment services|Certified designs, fleet-service records, engineering expertise and installed engines|AI can improve engineering, inspection and predictive maintenance while certification constrains deployment.|Long service relationships and contracted availability can reward lower maintenance cost.|Unscheduled removals per flight-hour; time on wing; service margin at equal contract mix|Flight safety, certification, life-cycle liabilities and inspection misses|Predictions fail on rare modes or lower maintenance activity reduces billable revenue|Evaluate matched fleets by engine variant, utilization and environment. Require independent engineering review.|2–5 years|S16
D05|Industrials|Waste, facilities and route-based business services|Local route density, asset records and recurring commercial contracts|AI can improve dispatch, sorting, service planning and customer support.|Density and recurring service relationships can retain some cost savings, especially where local capacity is scarce.|Cost per stop or tonne; contamination rate; contract contribution margin|Safety, service misses, capital costs and labor terms|Savings require disproportionate fleet investment or municipal contracts reprice them away|Compare matched routes and facilities and include replacement capex, training and exception handling.|1–3 years|S11
M01|Materials|Chemicals, industrial gases and specialty materials|Formulation libraries, application expertise, process plants and customer qualification|AI can propose formulations and optimize process conditions, improving experiment throughput and resource intensity.|Qualified formulations, long contracts and application support may retain value. Commodity producers face price pass-through.|Qualified products per R&D euro; energy per tonne at equal quality; plant uptime|Specification failures, scale-up reproducibility and customer qualification time|Laboratory improvements fail at production scale or feedstock and pricing overwhelm retained savings|Use blinded formulation tests and matched production runs. Distinguish specialty pricing from commodity cycle effects.|1–5 years|S17
M02|Materials|Mining, metals and resource extraction|Orebody knowledge, geological records, equipment fleets and processing plants|AI can improve grade control, ore sorting and maintenance, raising recoverable output from existing assets.|Low-cost resource owners may retain operational gains, but commodity prices and royalties remain dominant.|Recovery at fixed head grade; cost per recovered unit; availability|Reserve quality, incidents, ore depletion and sustaining capex|Reported gains reflect richer ore or prices, or model output fails at new deposits|Compare benches and processing runs with mineralogy and grade controls. Separate autonomy from commodity exposure.|1–4 years|S17
C01|Consumer Discretionary|E-commerce, marketplaces and discretionary retail|Transaction histories, seller networks, customer access and fulfillment or merchandising systems|AI can improve matching, inventory allocation and merchandising while reducing seller or service work.|Network density and distribution can capture gains through retention, service fees or advertising. Agents can also bypass storefronts.|Contribution per order after fulfillment; inventory turns at fixed availability; seller retention|Returns, subsidies, customer acquisition and seller economics|Agents commoditize discovery, advertising yield deteriorates or savings require permanent discounts|Run cohort or market tests controlling for subsidies, category mix and fulfillment speed.|6–24 months|S11
C02|Consumer Discretionary|Mobility, travel and reservation platforms|Demand density, supply relationships, transaction context and booking infrastructure|AI can improve matching, itinerary planning and support, increasing utilization and conversion.|Network access and transaction completion may retain value, but external agents can redirect customer relationships.|Contribution per trip or booking; repeat use; support cost per completed transaction|Cancellations, incentives, supplier terms and consumer protections|Agents route customers directly to suppliers, commissions fall or autonomy moves bargaining power to fleet owners|Evaluate matched geographic and customer cohorts. Separate AI conversion from travel cycles and promotional spending.|6–24 months|S11
C03|Consumer Discretionary|Automotive manufacturers and suppliers|Manufacturing expertise, engineering data, vehicle fleets and service distribution|AI can improve design, production quality and service diagnostics. Autonomous driving is a separate capital-intensive thesis.|Brand and differentiated vehicle economics must retain savings despite price competition.|Warranty cost per comparable vehicle; engineering hours per validated platform; factory yield|Recall rates, safety, residual values and software liability|Efficiency gains fail to offset price cuts, weak products or loss of geographic competitiveness|Benchmark matched models and plants. Treat autonomy R&D and commercial manufacturing productivity separately.|1–4 years|S16
C04|Consumer Discretionary|Consumer brands, apparel and luxury|Brand equity, product archives, direct customer relationships and distribution|AI can improve demand forecasting and product iteration while reducing marketing production cost.|Scarce brands and owned customer access may preserve pricing. Generic creative production offers little durable advantage.|Full-price sell-through; inventory turns; contribution after marketing|Brand dilution, returns, discounting and channel conflict|Cheaper content increases noise without improving demand or competitors match designs rapidly|Use product and region cohorts, separating price increases and channel shifts from AI improvements.|1–3 years|S11
S01|Consumer Staples|Food, beverages and household products|Formulation know-how, brands, distribution and manufacturing networks|AI can improve formulation, demand planning and plant operations.|Brand strength and efficient distribution may retain part of savings, but retailers and consumers can demand lower prices.|Waste and energy per unit; launch success by cohort; contribution after trade spend|Quality, recalls, promotions and raw-material costs|Cost savings simply finance promotions or innovation becomes less differentiated|Use matched plants and product cohorts controlling for input inflation, mix, pricing and trade spend.|1–4 years|S17
S02|Consumer Staples|Food retail and membership retail|Store networks, inventory flows, purchase histories and customer relationships|AI can improve replenishment, reduce spoilage and support store labor productivity.|Scale and repeat purchasing may reinforce advantage, while low-price promises deliberately transfer savings to customers.|Waste at equal availability; labor hours per basket; member renewal|Food safety, service quality, price investment and capex|Improved operations produce no durable margin or growth advantage because all savings fund lower prices|Compare matched stores and fulfillment zones, including labor scheduling quality and basket mix.|6–24 months|S11
T01|Communication Services|Telecommunications and connectivity|Network telemetry, spectrum, customer relationships and local infrastructure|AI can optimize network energy, fault resolution and service operations.|Network quality and lower cost can improve cash generation, but price competition and regulation may share gains.|Energy per traffic unit; fault repair time; cash cost per subscriber|Dropped calls, outages, churn and traffic growth|Traffic or new infrastructure explains improvements, while tariff pressure absorbs savings|Use staged network-cell deployments and service cohorts, controlling for equipment generation and traffic mix.|1–3 years|S12
T02|Communication Services|Advertising, media and entertainment platforms|Audience access, engagement signals, content libraries and recommendation systems|AI can improve recommendations and advertiser tools while lowering some production costs.|Distribution and measured outcomes may support monetization, but abundant content can erode creative scarcity and trust.|Incremental advertiser conversion; retention; contribution after content and compute costs|Ad load, privacy, content rights and user satisfaction|More engagement does not improve customer value, generic agents bypass discovery or content costs race upward|Use randomized recommendation and ad tests. Distinguish incremental conversion from attribution changes.|6–24 months|S01
E01|Energy|Oil, gas and energy services|Subsurface records, engineering workflows, operating assets and customer deployment channels|AI can improve reservoir interpretation, drilling decisions and predictive maintenance.|Resource ownership and differentiated services can retain some gains, subject to commodity cycles and contract repricing.|Nonproductive rig time; recovery or production at fixed geology; cost per unit|Safety, emissions, reservoir assumptions and sustaining capex|Higher output reflects geology or more investment, or customers capture service productivity|Compare wells by basin and design and normalize commodity prices and operational exposure.|1–4 years|S17
U01|Utilities|Electric, water and regulated infrastructure utilities|Grid or network telemetry, physical assets and local service obligations|AI can improve load forecasting, maintenance and dispatch or leakage management.|Incentive regulation or merchant exposure may retain gains. Allowed returns and rate reviews can transfer them to consumers.|Outage duration; network losses; controllable operating cost per customer|Reliability, affordability, cyber resilience and capital recovery|Regulatory resets remove all savings or load growth forces low-return capital spending|Compare service territories and asset cohorts. Model the actual regulatory sharing mechanism separately from AI load demand.|1–5 years|S17
R01|Real Estate|Property ownership, REITs and data centers|Locations, tenant relationships, building systems and operating scale|AI can improve maintenance, leasing support and energy management. Data-center rent growth is an AI-demand thesis with different economics.|Lease structure determines who keeps operating savings. Strong locations can support occupancy but do not guarantee an AI moat.|Same-property NOI at fixed occupancy; owner-retained energy savings; leasing cost|Tenant satisfaction, tenant concentration, capex and financing costs|Tenants receive all savings or debt and obsolescence overwhelm small operating benefits|Compare matched properties under identical lease structures. Separate rental market changes from technology effects.|1–3 years|S17;S13
R02|Real Estate|Property services and facilities intelligence|Transaction observations, facilities operations and client workflows|AI can improve building operations, valuation support and service delivery using property-specific context.|Recurring facilities contracts and workflow integration may retain savings, but client-owned data and fee competition constrain capture.|Contribution per facilities contract; work-order resolution cost; client renewal|Valuation errors, client data rights and service failures|Customers internalize the tools or fee cuts fully pass through labor savings|Use matched managed buildings and service contracts. Separate property transaction cycles from recurring service productivity.|6–30 months|S13
'''
AREAS = []
keys = ['id','sector','name','asset','mechanism','capture','kpi','guardrail','falsifier','experiment','horizon','source_ids']
for line in AREA_DATA.strip().splitlines():
    vals = line.split('|')
    assert len(vals)==len(keys), line
    d=dict(zip(keys,vals)); d['source_ids']=d['source_ids'].split(';'); AREAS.append(d)

SOURCES = [
('S01','Generative AI at Work, revised November 2024','https://arxiv.org/abs/2304.11771v2','2024-11-06','Research paper','5,172 support agents. AI assistance increased issues resolved per hour by 15% on average in this setting.','Task-level evidence in one setting, not a forecast for all firms or proof of retained profit.'),
('S02','METR experienced developer randomized trial','https://metr.org/blog/2025-07-10-early-2025-ai-experienced-os-dev-study/','2025-07-10','Research organization','16 developers and 246 tasks took 19% longer with early-2025 AI tools.','Historical tools and selected experienced developers. Read S18 before using this as a current capability assessment.'),
('S03','Sanofi artificial intelligence in R&D','https://www.sanofi.com/en/our-science/digital-artificial-intelligence/artificial-intelligence-rd','2023-09','Company description','Describes target identification, active learning for molecule design and integration of clinical and molecular data.','Dated deployment description. Does not demonstrate improved Phase II or Phase III success.'),
('S04','RELX 2025 annual report: market segments','https://www.relx.com/~/media/Files/R/RELX-Group/documents/reports/annual-reports/2025-ar-sections/relx-2025-market-segments.pdf','2026-02-19','Company annual report','Printed page 27 describes Protégé, authoritative content, citation validation and a multi-model approach.','Product and adoption claims are management-reported. They do not isolate incremental AI profit.'),
('S05','Thomson Reuters AI for professionals','https://www.thomsonreuters.com/en/artificial-intelligence','undated; accessed 2026-09-11','Company product page','CoCounsel combines professional content with workflow tools. FAQ says customer content and prompts are not used to train or improve its AI products or underlying models.','Commercial description and selected customer examples. Do not assume pooled customer-data training rights.'),
('S06','Wolters Kluwer tax and accounting solutions','https://www.wolterskluwer.com/en/solutions/tax-accounting-us','undated; accessed 2026-09-11','Company product page','Offers AI-powered tax, audit, workflow and firm-management tools.','Product availability supports a use-case lead, not incremental group-level financial returns.'),
('S07','Intuit Assist','https://www.intuit.com/intuitassist/','undated; accessed 2026-09-11','Company product page','Describes a generative AI financial assistant integrated with Intuit products.','No independently verified contribution margin or causal retention uplift established here.'),
('S08','SAP Joule and Business AI','https://www.sap.com/products/artificial-intelligence.html','undated; accessed 2026-09-11','Company product page','Describes agents operating with business context, integrations and tenant-level data isolation.','Customer data access is not equivalent to ownership or cross-customer training permission.'),
('S09','JPMorganChase 2025 COO shareholder letter','https://www.jpmorganchase.com/ir/annual-report/2025/ar-ceo-letter-jennifer-piepszak','2026-04-06','Company shareholder letter','Describes deployed AI in credit, fraud, personalization and employee workflows, with capacity reinvested in growth.','Management claims do not supply a controlled bank-wide AI profit bridge.'),
('S10','Visa Protect','https://www.visa.com/en-us/solutions/visa-protect','undated; accessed 2026-09-11','Company product page','Offers AI-supported authentication, authorization and payment-fraud decision services.','Product availability alone does not establish net fraud reduction or network shareholder capture.'),
('S11','Walmart technology and agentic commerce','https://corporate.walmart.com/about/technology','undated; accessed 2026-09-11','Company description','Describes deployed shopping, support, merchant and supply-chain applications.','Broad management descriptions. Do not extrapolate selected workflow claims to total retail margins.'),
('S12','Ericsson telecom AI','https://www.ericsson.com/en/ai','undated; accessed 2026-09-11','Supplier description','Explains AI for network automation, operations and network performance.','Supplier capability evidence, not demonstrated economics for Deutsche Telekom or Singtel.'),
('S13','CBRE data and technology','https://www.cbre.com/about-us/technology','undated; accessed 2026-09-11','Company description','Describes data and technology across real-estate services.','Use as a research lead for property workflows. No attributable AI profit established.'),
('S14','NAIC artificial intelligence in insurance','https://content.naic.org/insurance-topics/artificial-intelligence','2026-04-03','Regulatory association','Describes insurance uses in underwriting, pricing, claims and fraud and highlights oversight obligations.','Industry evidence cannot verify any named insurer. Survey use-or-plan-to-use figures are not adoption rates.'),
('S15','EIOPA opinion on AI governance and risk management','https://www.eiopa.europa.eu/publications/opinion-artificial-intelligence-governance-and-risk-management_en','2025-08-06','Supervisory authority','Sets out a risk-based and proportionate approach to AI governance in insurance.','An opinion is not a substitute for checking applicable jurisdictional requirements.'),
('S16','Synopsys AI solutions','https://www.synopsys.com/ai.html','undated; accessed 2026-09-11','Company product page','Describes AI capabilities for engineering and chip design.','Specific customer improvements need design constraints and validation costs. Not direct evidence for other industrial companies.'),
('S17','IEA Energy and AI: energy optimization and innovation','https://www.iea.org/reports/energy-and-ai/ai-for-energy-optimisation-and-innovation','2025-04-10','Intergovernmental analysis','Distinguishes AI applications in energy operations from electricity demand for AI infrastructure.','Technical potential and scenarios are not realized returns for individual companies.'),
('S18','METR update to developer productivity experiment','https://metr.org/blog/2026-02-24-uplift-update/','2026-02-24','Research organization','Follow-up explains selection and measurement problems when evaluating newer AI tools.','Do not treat the historical slowdown as a current universal effect, or newer biased samples as a precise universal speedup.'),
('S19','MSCI Global Industry Classification Standard','https://www.msci.com/indexes/index-resources/gics','accessed 2026-09-11','Index taxonomy','Provides the broad 11-sector reference used as a coverage checklist.','This repository uses its own research areas and does not claim official GICS classifications for companies.'),
]
SOURCES += [
('S20','Siemens introduces AI agents for industrial automation','https://press.siemens.com/global/en/pressrelease/siemens-introduces-ai-agents-industrial-automation','2025-05-12','Company press release','Describes available engineering and operations copilots, customer implementations and an agent architecture.','The headline productivity ambition is a target. Pilot maintenance results are not group-level margin evidence.'),
('S21','Amazon million robots and DeepFleet model','https://www.aboutamazon.com/news/operations/amazon-million-robots-ai-foundation-model','undated; accessed 2026-09-11','Company announcement','Describes an AI model for coordinating robot travel within Amazon fulfillment operations.','Operational claims do not isolate return on total robotics investment or consolidated AI profit.'),
('S22','CrowdStrike Charlotte AI','https://www.crowdstrike.com/en-us/platform/charlotte-ai/','undated; accessed 2026-09-11','Company product page','Offers an AI analyst for security investigation and response workflows.','Vendor claims require independent detection-quality and cost evaluation.'),
]
for a in AREAS:
    if a['id']=='I08': a['source_ids']=['S22']
    if a['id']=='D01': a['source_ids']=['S20','S17']
    if a['id']=='D03': a['source_ids']=['S21']
    if a['id']=='I06': a['source_ids']=['S21','S17']
SOURCES=[dict(zip(['id','title','url','published','type','claim','limitation'],x),accessed=DATE) for x in SOURCES]
SM={s['id']:s for s in SOURCES}

def build_areas():
    rows=[]
    for a in AREAS:
        slug=a['id'].lower()+'-'+a['name'].lower().replace(',','').replace(' ','-')
        a['path']='industries/'+slug+'.md'
        srefs='\n'.join(f"- [{sid}: {SM[sid]['title']}]({SM[sid]['url']}). See the source register for the supported claim, scope and limitation." for sid in a['source_ids'])
        # These are designed research tests, not claimed observed results.
        metrics=a['kpi'].split('; ')
        kpirows='\n'.join(f'| {m} | Obtain a pre-deployment baseline and matched comparison | Require sustained improvement net of full implementation cost | {a["guardrail"]} |' for m in metrics)
        write(a['path'],f'''# {a['name']}

**Area:** {a['id']} · **Sector coverage:** {a['sector']} · **Version:** 0.1 · **As of:** {DATE}

**Status: research hypothesis.** Mechanisms and tests below are analyst proposals, not established results for all companies in the area. The evidence paragraph identifies what the cited sources actually support. Company-level verification and valuation remain separate gates.

## The incumbent asset

{a['asset']}. Research must establish who owns each input, what can be licensed or replicated, and whether usage rights permit inference, retrieval, product improvement or pooled training. Those are four different permissions.

## The AI advantage

{a['mechanism']}

The proposed feedback loop is operational: additional activity creates observed outcomes, which improve the next decision only if the outcomes are accessible, representative and lawfully reusable. A faster interface alone does not establish a learning advantage. Separate established optimization or machine learning from incremental generative or agentic capabilities.

## Who retains the gain

{a['capture']} Identify the invoice, contract, patent, fee schedule or internal cost line through which value reaches shareholders. Compare the benefit with spending on data preparation, inference, integration, validation and physical deployment.

## Research criteria

| Test | Evidence required | Failure or unresolved outcome |
|---|---|---|
| Asset advantage | Inventory of the specific inputs above, provenance, data contracts and a credible replication-cost comparison | Mere data volume, public records, or access without usage rights |
| Incremental AI lift | {a['experiment']} | A demo, a self-reported time estimate or a comparison against an obsolete baseline |
| Operational deployment | Production scope, eligible workload denominator, named process owner and exception rate | Pilot activity with no scaled workflow adoption |
| Economic capture | Reconcile the KPIs below to segment cash earnings and customer pricing | Gains absorbed by price cuts, revenue cannibalization or supplier fees |
| Durability | Compare rival offerings, customer portability and the rate of new useful feedback | A generic model or common vendor reproduces the benefit |
| Quality and risk | {a['guardrail']} | Material harm, hidden liabilities or quality decline |

## Measurement contract

| KPI | Baseline and comparator | Promotion criterion | Controls |
|---|---|---|---|
{kpirows}

Set a company-specific minimum economically meaningful effect before examining results. Quantify sample size, uncertainty and seasonal or cohort effects. Default financial materiality trigger: a credible path to at least 5% of normalized operating profit within five years. This is an analyst screening convention, not an observed industry threshold. Use risk-adjusted pipeline economics for pharma and capital-adjusted earnings for financial firms.

**Expected observation window:** {a['horizon']}. This is a research planning assumption, not a forecast.

## Falsification

{a['falsifier']}. Downgrade the thesis if this persists in a properly controlled evaluation. Lack of disclosed evidence means unproven, not necessarily disproven.

## Evidence and confidence

{srefs}

Where a source describes an adjacent industry or supplier, it supports technical plausibility only. It does not verify deployment by this area's candidates. Confidence is moderate in the proposed mechanism and low in durable shareholder capture until company-specific evidence is collected. See [the evidence standard](../framework/research-standard.md).

## Candidate work

Filter `primary_area` or `secondary_areas` in [companies.csv](../universe/companies.csv). Membership initiates research. Complete [the company memo](../framework/company-memo-template.md), including a challenger comparison, before advancing any name to valuation.
''')
        rows.append(f"| {a['id']} | {a['sector']} | [{a['name']}]({Path(a['path']).name}) | {a['kpi'].split(';')[0]} |")
    write('industries/README.md','# Industry thesis library\n\n36 research areas cover all 11 broad equity sectors. These are analytical groupings, not an official GICS subindustry register. Each area defines the asset, AI mechanism, capture path, measurement contract and falsifier before company selection.\n\n'+ '| ID | Broad sector | Research area | First proof metric |\n|---|---|---|---|\n'+'\n'.join(rows)+'\n\nSee [coverage and boundary cases](../framework/coverage.md) for specialist businesses, weak-fit areas and omissions.\n')

if __name__=='__main__':
    build_areas()
    write('sources/source-register.json',json.dumps(SOURCES,indent=2)+'\n')
    write('industries/areas.json',json.dumps(AREAS,indent=2)+'\n')
    write('sources/README.md','# Source register\n\nResearch cut-off: '+DATE+'. Links below were opened during this build. Publication dates may be older than the access date. Only the specific evidence stated is claimed as verified. Company marketing receives less weight than independently measured outcomes. No full third-party reports are redistributed.\n\n'+ '\n\n'.join(f"## {s['id']} — {s['title']}\n\n[{s['type']}]({s['url']}) · Published: {s['published']} · Accessed: {s['accessed']}\n\n**Supported:** {s['claim']}\n\n**Limit:** {s['limitation']}" for s in SOURCES)+'\n\n## Supplied origin documents\n\n- [Original regime](ai_incumbent_productivity_regime.md), preserved unchanged.\n- [Universe build brief](build-the-AI-Incumbent-Productivity-Universe.txt), preserved unchanged.\n\nThe original 14-dimension score is a starting hypothesis. The operational framework separates structural priors, evidence and valuation rather than inheriting its suggested buy thresholds.\n')
    print(f'Built {len(AREAS)} industry theses and {len(SOURCES)} source records.')
